[workspace]
resolver = "2"
members = [
    "chronos-core",
    "chronos-mem",
    "chronos-io",
    "chronos-replicate",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"

[workspace.dependencies]
crossbeam = "0.8"
blake3 = "1.5"
thiserror = "1.0"
parking_lot = "0.12"
io-uring = "0.6"
libc = "0.2"
