[package]
name = "chronos-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
chronos-mem = { path = "../chronos-mem" }
chronos-io = { path = "../chronos-io" }
chronos-replicate = { path = "../chronos-replicate" }
crossbeam = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
